# Generated by Django 6.0.3 on 2026-04-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_category_description_category_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
    ]
